#!/bin/bash
sas_id=${1}

function remote_parset_lookup() {
    parset_host=$1
    sas_id=$2
    parset_key=$3

    ssh $parset_host "grep $parset_key /localhome/lofarsystem/parsets/rtcp-$sas_id.parset" 2>/dev/null;
}


function sas_id_project() {
    sas_id=$1
    remote_parset_lookup lofarsys@cbm001 $sas_id 'Observation.Campaign.name'|sed -e's/=/ /g' -e 's/"/ /g'|awk '{ print $2 }';
}


function hostname_fqdn() {
    # Return the fully qualified domain name of a LOFAR server
    # Sadly -- on some machines -- hostname returns the FQDN
    # while hostname -f returns the short name >_<
    (hostname;hostname -f)|awk '{ print length, $0 }' | sort -n -s | cut -d" " -f2-
}


project_id=`sas_id_project ${sas_id}`

case `hostname_fqdn` in
    lhn00*)
        INSPECT_ROOT=/globaldata/inspect
        echo "report_global_status for ${sas_id}"
        if [[ ! -e  ${INSPECT_ROOT}/${sas_id}/file-sizes.txt ]] ; then
            echo "  - determining file sizes"
            cexec locus: "du --apparent-size -sm /data/L${sas_id}/*" > ${INSPECT_ROOT}/${sas_id}/file-sizes.txt
        fi
        sleep 2
        if [[ ! -e  ${INSPECT_ROOT}/${sas_id}/rtcp-${sas_id}.loss ]] ; then
            echo "  - determining input losses"
            ssh -A cbt001-10gb01 "tail -100000 log/rtcp-${sas_id}.log|grep loss|sort -k 8"|grep GPUProc > ${INSPECT_ROOT}/${sas_id}/rtcp-${sas_id}.loss
        fi
        sleep 2
        if [[ ! -e  ${INSPECT_ROOT}/${sas_id}/rtcp-${sas_id}.errors ]] ; then
            echo "  - determining warnings / errors"
            ssh -A cbt001-10gb01 "egrep 'ERR|WARN|FATAL|runObservation|xception|acktrace|\#(0|1|2|3|4|5|6|7|8|9) |Signalling|Alarm|SIG|feed-back|Result code' log/rtcp-${sas_id}.log"|grep -v Flagging > $INSPECT_ROOT/${sas_id}/rtcp-${sas_id}.errors
        fi
        ;;


    *)
        INSPECT_ROOT=/dev/shm
        echo "report_global_status for ${sas_id}"
        mkdir -p ${INSPECT_ROOT}/${sas_id}
        if [[ ! -e  ${INSPECT_ROOT}/${sas_id}/file-sizes.txt ]] ; then
            echo "  - determining file sizes"
            du -b --apparent-size -sm /data/projects/${project_id}/L${sas_id}/*/* > ${INSPECT_ROOT}/${sas_id}/file-sizes.txt
        fi
        sleep 2
        if [[ ! -e  ${INSPECT_ROOT}/${sas_id}/f0seqnr-sizes.txt ]] ; then
            echo "  - determining f0seqnr sizes"
            du -b --apparent-size /data/projects/${project_id}/L${sas_id}/uv/*/table.f0seqnr > ${INSPECT_ROOT}/${sas_id}/f0seqnr-sizes.txt
        fi
        sleep 2
        if [[ ! -e  ${INSPECT_ROOT}/${sas_id}/rtcp-${sas_id}.loss ]] ; then
            echo "  - determining input losses"
            ssh -A cbm001 "tail -100000 log/rtcp-${sas_id}.log|grep loss|sort -k 8"|grep GPUProc > ${INSPECT_ROOT}/${sas_id}/rtcp-${sas_id}.loss
        fi
        sleep 2
        if [[ ! -e  ${INSPECT_ROOT}/${sas_id}/rtcp-${sas_id}.errors ]] ; then
            echo "  - determining warnings / errors"
            ssh -A cbm001 "egrep 'ERR|WARN|FATAL|runObservation|xception|acktrace|\#(0|1|2|3|4|5|6|7|8|9) |Signalling|Alarm|SIG|feed-back|Result code' log/rtcp-${sas_id}.log"|grep -v Flagging > $INSPECT_ROOT/${sas_id}/rtcp-${sas_id}.errors
        fi
        sleep 2
        # Try to obtain the parset named Lxxxxxx.parset first
        if [[ ! -e  ${INSPECT_ROOT}/${sas_id}/L${sas_id}.parset ]] ; then
            echo "   - checking for L${sas_id}.parset in /localhome/lofarsystem/log"
            scp cbm001:/localhome/lofarsystem/log/L${sas_id}.parset ${INSPECT_ROOT}/${sas_id}/L${sas_id}.parset

            # If the Lxxxxxx parset has not been copied, try to obtain the parset named rtcp-xxxxxx.parset
            if [[ ! -e  ${INSPECT_ROOT}/${sas_id}/L${sas_id}.parset ]] ; then
                echo "   - checking for rtcp-${sas_id}.parset in /localhome/lofarsystem/parsets/"
                scp cbm001:/localhome/lofarsystem/parsets/rtcp-${sas_id}.parset ${INSPECT_ROOT}/${sas_id}/rtcp-${sas_id}.parset
            else
                echo "   - existing parset found: ${INSPECT_ROOT}/${sas_id}/rtcp-${sas_id}.parset"
            fi
        else
            echo "   - existing parset found: ${INSPECT_ROOT}/${sas_id}/L${sas_id}.parset"
        fi
        ;;
esac
              
              
